## Preprocessing

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
#  YOUR CODE GOES HERE
application_df = application_df.drop(["EIN", "NAME"], 1)
application_df.head()

<ipython-input-2-2d68d3c6bb00>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  application_df = application_df.drop(["EIN", "NAME"], 1)

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
#  YOUR CODE GOES HERE
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
#  YOUR CODE GOES HERE
application_counts = application_df["APPLICATION_TYPE"].value_counts()
application_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
application_counts[application_counts < 500].index

Index(['T9', 'T13', 'T12', 'T2', 'T25', 'T14', 'T29', 'T15', 'T17'], dtype='object')

In [6]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
#  YOUR CODE GOES HERE
application_types_to_replace = list(application_counts[application_counts < 500].index)
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [7]:
# Look at CLASSIFICATION value counts for binning
#  YOUR CODE GOES HERE
class_counts = application_df["CLASSIFICATION"].value_counts()
class_counts

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [8]:
# You may find it helpful to look at CLASSIFICATION value counts >1
#  YOUR CODE GOES HERE
class_counts[class_counts > 1]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [9]:
class_counts[class_counts > 10]

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
Name: CLASSIFICATION, dtype: int64

In [10]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
#  YOUR CODE GOES HERE
classifications_to_replace = list(class_counts[class_counts < 1000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [11]:
# Convert categorical data to numeric with `pd.get_dummies`
#  YOUR CODE GOES HERE
application_with_dummies_df = pd.get_dummies(application_df)
application_with_dummies_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34295,1,5000,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,1,0
34296,1,5000,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,1,0
34297,1,5000,1,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
34298,1,36500179,0,0,0,0,1,0,0,0,...,0,0,0,0,1,0,0,0,1,0

In [12]:
# Split our preprocessed data into our features and target arrays
#  YOUR CODE GOES HERE
X = application_with_dummies_df.drop(["IS_SUCCESSFUL"], axis="columns").values
y = application_with_dummies_df["IS_SUCCESSFUL"].values
# Split the preprocessed data into a training and testing dataset
#  YOUR CODE GOES HERE
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=78)

In [13]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [14]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
#  YOUR CODE GOES HERE
number_input_feature = len(X_train[0])
hidden_nodes_layers1 = 80
hidden_nodes_layers2 = 30

nn = tf.keras.models.Sequential()

# First hidden layer
#  YOUR CODE GOES HERE
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layers1, input_dim=number_input_feature, activation="relu")
)

# Second hidden layer
#  YOUR CODE GOES HERE
nn.add(
    tf.keras.layers.Dense(units=hidden_nodes_layers2, activation="relu")
)


# Output layer
#  YOUR CODE GOES HERE
nn.add(
    tf.keras.layers.Dense(units=1, activation="sigmoid")
)
# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 80)                3520

 dense_1 (Dense)             (None, 30)                2430

 dense_2 (Dense)             (None, 1)                 31

=================================================================
Total params: 5981 (23.36 KB)
Trainable params: 5981 (23.36 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [15]:
# Compile the model
#  YOUR CODE GOES HERE
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [16]:
# Train the model
#  YOUR CODE GOES HERE
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 6s 5ms/step - loss: 0.5700 - accuracy: 0.7228
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5558 - accuracy: 0.7299
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5530 - accuracy: 0.7309
Epoch 4/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5511 - accuracy: 0.7326
Epoch 5/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5503 - accuracy: 0.7310
Epoch 6/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5486 - accuracy: 0.7322
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5481 - accuracy: 0.7325
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5480 - accuracy: 0.7344
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5465 - accuracy: 0.7341
Epoch 10/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5463 - accuracy: 0.7338
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5461 - accuracy: 0.7324
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5454 - accuracy: 0.7346
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5453 - accuracy: 0.7353
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5448 - accuracy: 0.7347
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5448 - accuracy: 0.7350
Epoch 16/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5443 - accuracy: 0.7357
Epoch 17/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5439 - accuracy: 0.7363
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5432 - accuracy: 0.7361
Epoch 19/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5429 - accuracy: 0.7362
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5432 - accuracy: 0.7352
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7377
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7366
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7369
Epoch 24/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7372
Epoch 25/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5419 - accuracy: 0.7379
Epoch 26/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5412 - accuracy: 0.7382
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5415 - accuracy: 0.7379
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5413 - accuracy: 0.7377
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5412 - accuracy: 0.7381
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7395
Epoch 31/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5407 - accuracy: 0.7385
Epoch 32/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5407 - accuracy: 0.7384
Epoch 33/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5406 - accuracy: 0.7387
Epoch 34/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5404 - accuracy: 0.7386
Epoch 35/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7387
Epoch 36/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5399 - accuracy: 0.7393
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7379
Epoch 38/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5398 - accuracy: 0.7399
Epoch 39/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5395 - accuracy: 0.7399
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7388
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7392
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7392
Epoch 43/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5390 - accuracy: 0.7397
Epoch 44/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5396 - accuracy: 0.7397
Epoch 45/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7389
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7399
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5385 - accuracy: 0.7396
Epoch 48/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5389 - accuracy: 0.7393
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7388
Epoch 50/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7393
Epoch 51/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5385 - accuracy: 0.7394
Epoch 52/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5383 - accuracy: 0.7393
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7402
Epoch 54/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5380 - accuracy: 0.7407
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5382 - accuracy: 0.7394
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7400
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7393
Epoch 58/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5380 - accuracy: 0.7395
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7410
Epoch 60/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7398
Epoch 61/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5374 - accuracy: 0.7410
Epoch 62/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7402
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5379 - accuracy: 0.7399
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7402
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7403
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7405
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7397
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7407
Epoch 69/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5369 - accuracy: 0.7407
Epoch 70/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7400
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7407
Epoch 72/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5373 - accuracy: 0.7409
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5370 - accuracy: 0.7408
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7400
Epoch 75/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7407
Epoch 76/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5363 - accuracy: 0.7404
Epoch 77/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7406
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7410
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7408
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7411
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7400
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7410
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7413
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5359 - accuracy: 0.7412
Epoch 85/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5361 - accuracy: 0.7402
Epoch 86/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5359 - accuracy: 0.7406
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5361 - accuracy: 0.7408
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7408
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7402
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7406
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7405
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7403
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5361 - accuracy: 0.7406
Epoch 94/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7407
Epoch 95/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5358 - accuracy: 0.7411
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5355 - accuracy: 0.7407
Epoch 97/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5353 - accuracy: 0.7413
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7408
Epoch 99/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5355 - accuracy: 0.7404
Epoch 100/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5350 - accuracy: 0.7406

In [19]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5562 - accuracy: 0.7261 - 385ms/epoch - 1ms/step
Loss: 0.5562055110931396, Accuracy: 0.726064145565033

In [21]:
# Export our model to HDF5 file
#  YOUR CODE GOES HERE
nn.save("AlphabetSoupCharity.h5")